chore: pin python-json-logger to older version
newer version has incorrect dependencies and app fails with
```
  File /sha-extractor-venv/lib64/python3.11/site-packages/pythonjsonlogger/utils.py, line 38, in package_is_available
    raise MissingPackageError(name, extras_name)
pythonjsonlogger.exception.MissingPackageError: The 'msgspec' package is required but could not be found.
```